### ISSUE TITLE
지향성 퍼징

### ISSUE THREAD

**Issue by KihongHeo** [prosyslab/pl-wiki#1]
페이지 추가 부탁

**Comment by goodtaeeun** [comment]
페이지라 하시면 저희 show-and-tell 레포처럼 마크다운 문서 형식으로 지향성 퍼징에 대해 설명하는 글을 올리도록 할까요?

**Comment by goodtaeeun** [comment]
아, 혹시 Wiki 페이지를 말씀하시는 건가요?

**Comment by goodtaeeun** [comment]
영광스러운 첫 페이지 작성 완료했습니다.
