### ISSUE TITLE
번역검산

### ISSUE THREAD

**Issue by KihongHeo** [prosyslab/pl-wiki#2]
추가부탁

**Comment by Hhro** [comment]
작성 완료하였습니다.

**Comment by KihongHeo** [comment]
아주 잘썼네.

**Comment by Hhro** [comment]
감사합니다.

**Comment by KihongHeo** [comment]
지향성 퍼징 문서처럼 윗첨자에 링크를 걸어주길 바란다.

**Comment by Hhro** [comment]
넵. 링크 걸어두었습니다.

**Comment by KihongHeo** [comment]
아, 내 말은 태은이가 한것처럼, 윗 첨자를 누르면 맨 아래 참고 문헌으로 뛰고, 그 참고문헌에다 링크를 걸어서 원본 논문으로 가게 만들면 어떨까 한것이었따.

**Comment by Hhro** [comment]
아하 그런 뜻이었군요. 반영해두었습니다.
