### ISSUE TITLE
fuzzing 을 뭐라 번역해야 쉬울까요?

### ISSUE THREAD

**Issue by kwangkeun** [prosyslab/pl-wiki#6]
아기(원숭이)가 스위치가 있는 장난감을 받아서 마구 스위치를 누르면서 기어이 장난감을 고장내고 마는 장면이 연상되는 단어가 뭘까요? "마구잡이"? "도장깨기"라는 단어도 떠오르네요.

sw fuzzing: 마구잡이 sw깨기 ?
directed fuzzing: 방향을 가지고 마구잡이깨기 ?

**Comment by kwangkeun** [comment]
마구잡이 sw괴롭히기
방향을 가지고 마구잡이괴롭히기

재미있네요.

**Comment by kwangkeun** [comment]
노림수를 가지고 마구잡이괴롭히기

**Comment by kwangkeun** [comment]
> 노림수를 가지고 마구잡이괴롭히기

노리는방향으로 마구잡이괴롭히기

**Comment by goodtaeeun** [comment]
안녕하세요 이광근 교수님!
퍼징의 적절한 번역을 저도 참 많이 생각해보았는데, 가장 최근에 떠오른 생각은 원어적 의미를 반영한 "삐죽빼죽 찔러보기"였습니다.

**Comment by kwangkeun** [comment]
> 안녕하세요 이광근 교수님! 퍼징의 적절한 번역을 저도 참 많이 생각해보았는데, 가장 최근에 떠오른 생각은 원어적 의미를 반영한 "삐죽빼죽 찔러보기"였습니다.

그것도 좋네요. 그렇게 왜 안쓰셨어요? 단 영문은 괄호에 꼭 넣으시고요. 공부의 언어와 일상의 언어가 굳이 구분될 필요가 없다고 봅니다 저는. 

나는 마구잡이괴롭히기 마구잡이로sw깨기 등으로도 쓰고 영문은 괄호에 꼭 넣고. 그렇게 여러가지가 시도되고 자연스래 그 중에서 하나로 수렵되는 시끌벅적 활기찬 생태계가 필요합니다.

**Comment by kwangkeun** [comment]
그리고 "원어적 의미를 반영한" 보다는 "그 기술을 정확히 이해해서 쉽게 어깨힘빼고" 로 생각해요 우리. ㅋ

**Comment by KihongHeo** [comment]
교수님 안녕하세요. 관심과 문제제기 해주셔서 감사드립니다. 퍼징은 꾸준히 생각해보고 있는 용어인데 더 적극적인 시도를 해보겠습니다.

사람들의 입에 자주 담기는 용어가 되기 위해서는 언어의 경제성도 중요할 것 같습니다. 경험상 "어날리시스" 보다 "분석" 이 더 편한 이유가 더 짧기 때문이라 생각합니다. 그래서 저는 마구잡이로 휘갈긴다는 것을 짧게 표현한다는 측면에서 "난사"도 괜찮은 것 같습니다.

**Comment by goodtaeeun** [comment]
말씀 감사합니다 교수님 ㅎㅎ "어깨힘빼고"라는 말이 개인적으로 마음에 잘 와닿는것 같습니다.

**Comment by kwangkeun** [comment]
> 교수님 안녕하세요. 관심과 문제제기 해주셔서 감사드립니다. 퍼징은 꾸준히 생각해보고 있는 용어인데 더 적극적인 시도를 해보겠습니다.
> 
> 사람들의 입에 자주 담기는 용어가 되기 위해서는 언어의 경제성도 중요할 것 같습니다. 경험상 "어날리시스" 보다 "분석" 이 더 편한 이유가 더 짧기 때문이라 생각합니다. 그래서 저는 마구잡이로 휘갈긴다는 것을 짧게 표현한다는 측면에서 "난사"도 괜찮은 것 같습니다.

"난사로 sw깨기" 이렇게 되나요??

**Comment by KihongHeo** [comment]
네 교수님. 재미있고 좋습니다.
